kind: Namespace
apiVersion: v1
metadata:
  name: model-server
  labels:
    kubernetes.io/metadata.name: model-server
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: model-server
